### ISSUE TITLE
Question: What is needed to add a new language to quicktype?

### ISSUE THREAD

**Issue by borgdylan** [quicktype/quicktype#1029]
I have my own compiler targeting .NET that compiles a langauge other than C#. Is it allowable to fork the C# support for quicktype and use it as a base for supporting my language?

**Comment by schani** [comment]
Yes, of course!  quicktype is open source :-)

You don't actually have to fork the whole of quicktype.  Instead you can use quicktype-core as a library and just give it your custom target language and renderer.  [This blog post](https://blog.quicktype.io/customizing-quicktype/) shows how to do that.  Instead of subclassing `CSharpTargetLanguage` and `CSharpRenderer`, like in the blog post, you'd copy one of the existing ones into your project, rename them, and then change them to work for your language.

If you have an questions at all, please talk to use [on Slack](http://slack.quicktype.io).

**Comment by borgdylan** [comment]
Is it possible to add a module in that way to quicktype itself? I wanted my addition to be invokable by the vscode addin invoking quicktype. I already have a language extension that assigns a language-id to source files.

**Comment by schani** [comment]
Is your programming language used by a wider community?  If so, it would make total sense to add it to quicktype.  If not, I'm not sure how we could make this possible.  I don't think you can add extension to VSCode extensions...  You could certainly fork the extension and publish your own with support for your language.  If you have a better idea, please let me know.  My main concern is breaking changes in quicktype, and how to make sure the community languages still work and don't drift away.

**Comment by borgdylan** [comment]
My plan was to have a fork that is not published. The language is not used by many people. I plan to patch the extension manually without having my changes be in the offical code bases.

**Comment by schani** [comment]
Sounds good.  Like I said, we're happy to help if you're stuck.

**Comment by ocapmycap** [comment]
For anyone finding this via search engine: The link to the blog post mentioned by @schani above has been updated to [here](https://quicktype.io/blog/customizing-quicktype).
