### ISSUE TITLE
Keys with Underscore are Wrongly Converted

### ISSUE THREAD

**Issue by darrabam** [quicktype/quicktype#1138]
Hi,
This json:
`{"access_token":"H4sIAAAAAAAAAOVXa2wUVR","expires_in":7200,"token_type":"Access Token"}`

Choosing (C# language) gets converted to:

> public partial class ANYNAME
> {
>     public string AccessToken { get; set; }
>     public long ExpiresIn { get; set; }
>     public string TokenType { get; set; }
> }

However, the result class will make the Json converter (.net Newtonsoft.Json) return null. This is due to removing the _ in the keys. The correct way is to keep _ as part of the variable name.

Thanks,

**Comment by schani** [comment]
This is by design: quicktype generates names that correspond to the C# naming conventions.  If you need to serialize/deserialize JSON, please use either "Complete" or "Attributes only" output features:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/61363/49876358-0f85f280-fdd8-11e8-9b41-22b87063a14e.png">
