### ISSUE TITLE
No types emitted when flat JSON has 50+ keys (all string values)

### ISSUE THREAD

**Issue by jcfranco** [quicktype/quicktype#1479]
I noticed an issue when trying to generate TS types from a flat JSON file w/ 50 keys (see [repro case](https://app.quicktype.io?share=m6LDrL1f20QXpnG7isIM)). It generates the types fine as soon as you remove one line or if you [add a non-string value](https://app.quicktype.io?share=J1LSraFF9byQ5sI47RfY).

**Comment by skornel02** [comment]
I think the problem here is that no custom types are being created, because after a certain threshold it gets optimized into a map (or object in typescript). 
You might want to disable 'Detect maps' feature under the other settings. [case with feature disabled](https://app.quicktype.io?share=G8OFS4DHvsuYHqmrUx3O)
Related: #1477

**Comment by jcfranco** [comment]
Thanks for the quick response and workaround!

**Comment by dvdsgl** [comment]
Yes, this is map detection, which you can disable.
