### ISSUE TITLE
Problems when parsing floats and ints

### ISSUE THREAD

**Issue by znx3p0** [quicktype/quicktype#1663]
When parsing JSON to a statically typed language(tested in Go and Rust), Quicktype confuses floats with ints whenever the float ends with a zero.

```json
{
    "bar": 2.0
}
```
This JSON input produces the following rust code
```rust
#[derive(Serialize, Deserialize)]
pub struct Foo {
    pub bar: i64,
}
```
The JSON file has a floating point, but Quicktype confused the float as an int.
But if the number does not end with a zero, it is parsed correctly.
```json
{
    "bar": 2.1
}
```
Produces
```rust
#[derive(Serialize, Deserialize)]
pub struct Foo {
    pub bar: f64,
}
```

**Comment by dvdsgl** [comment]
Yes, unfortunately we use `JSON.parse` which does not allow us to distinguish `2.0` from `2`—we'll need our own JSON parser, I believe.

**Comment by pparce** [comment]
I solved this problem by replacing all occurrences of ".0" by ".1" in my JSON

**Comment by aodennison** [comment]
I saw the problem, when the value is 0.0. I was impressed that @znx3p0 looked at other cases, but I think his description goes a bit too far. The issue is not when the value ends with 0, but when the value's decimal part is 0 and can be represented as an integer. Thus 0.0 and 2.0 are incorrectly treated as int, but 2.10 which ends with 0 but is correctly recognized as a float.  (The trailing, insignificant zero is commonly seen in US currency.)
