### ISSUE TITLE
Generate model from FHIR Schema

### ISSUE THREAD

**Issue by JonasDaWi** [quicktype/quicktype#1975]
I would like to generate kotlin classes from the [FHIR Schema](https://hl7.org/fhir/definitions.json.zip). The problem is that quicktype crashes with 
`Error: Maximum call stack size exceeded.`
 When I set a higher stack size using e.g. `node --stack-size=9840000 --max-old-space-size=12000` node crashes with following error:
`7540 segmentation fault (core dumped)  node --stack-size=9840000 --max-old-space-size=12000 dist/cli/index.js -s`

Does someone know what else I can try?

**Comment by schani** [comment]
_Triage sweep note (assisted by Claude): confirmed reproducible on current master (v23.3.0, `68ecb284`). Noting this issue is closed, but the underlying crash still reproduces, so leaving these findings here in case it's useful if anyone revisits it._

Reproduced the crash with the official `fhir.schema.json` (4.3 MB, ~800 interlinked definitions, from [hl7.org/fhir/definitions.json.zip](https://hl7.org/fhir/definitions.json.zip) as linked in the issue):
```
node dist/index.js --lang kotlin --src-lang schema fhir.schema.json -o fhir.kt
```
→ `Error: Maximum call stack size exceeded`. The crash is language-independent (also fails with `--lang typescript`), so it's a core issue, not a Kotlin emitter issue.

**Root cause:** stack trace bottoms out in `GraphRemapBuilder.forceReconstituteTypeRef` → `TypeReconstituter.reconstitute` → `ObjectType.reconstitute`, in `packages/quicktype-core/src/GraphRewriting.ts` and `src/Type/Type.ts`. These recurse per-type with no explicit worklist/iteration, so the reconstitution depth is bounded only by the native JS call stack, not by any quicktype-imposed limit. With `node --stack-size=8000` the overflow goes away, but then processing this schema exceeds 500s, so there's a secondary scalability problem in the same code path (recursion is presumably also doing more work than necessary per node).

**Assessment:** severity high (deterministic crash with default options on real-world input — the official FHIR schema is a legitimate, sizeable schema people plausibly want to process, and there's no workaround via CLI flags), fix difficulty hard: the recursive reconstitute-per-type pattern underlies every rewrite/remap pass in the type graph, so converting it to an iterative/worklist-based approach touches core machinery, not a localized fix, and the secondary performance issue would still need separate work.

**Reproduction:** input is the public FHIR schema linked above (`fhir.schema.json` inside `definitions.json.zip`), too large to inline (4.3 MB).
