### ISSUE TITLE
Generate Equatable and Hashable in Swift

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#220]
```swift
extension Country: Equatable, Hashable {
  static func == (lhs: Country, rhs: Country) -> Bool {
    return lhs.name == rhs.name &&
    lhs.capital == rhs.capital &&
    lhs.visited == rhs.visited
  }

  var hashValue: Int {
    return name.hashValue ^ capital.hashValue ^ visited.hashValue
  }
}
```

**Comment by ffittschen** [comment]
Generating the methods, e.g. `static func == (lhs: Country, rhs: Country) -> Bool` might not be necessary since Swift 4.1 will synthesize conformance to `Equatable` and `Hashable`: https://github.com/apple/swift-evolution/blob/master/proposals/0185-synthesize-equatable-hashable.md

If I read the proposal correctly, you only need to _opt-in_ by declaring conformance without implementing the methods, so this would be sufficient:
```swift
extension Country: Equatable, Hashable { }
```

**Comment by dvdsgl** [comment]
Wow! That’s fantastic.

**Comment by bielikb** [comment]
fyi, Swift 4.1 will be out around Spring 2018 or later.
