### ISSUE TITLE
Error: Cannot handle a class type that's also a map.

### ISSUE THREAD

**Issue by waywardmonkeys** [quicktype/quicktype#526]
Again, this is when using the Vega Lite schema (versions of which can be found here: https://github.com/vega/schema)

When I work around issue #525 by removing `"format": "uri"` from my input ... I get an error about "Cannot handle a class type that's also a map", but no indication where in the file (which is large) that this is happening ...

What causes this or what can I look for in the JSON schema input?

**Comment by schani** [comment]
It can happen when you use `oneOf` or `anyOf` where one of the cases is a type with specific properties and another case is one where `additionalProperties` is set.  See #493

**Comment by schani** [comment]
Sorry about the bad error reporting.

**Comment by schani** [comment]
I wanted to see what [schemafy](https://github.com/Marwes/schemafy) makes out of that Vega schema, but it seems it's a library.  I'm not a Rust user - could you tell me how to use schemafy to generate code from schema, or link me to the output for that schema?

**Comment by waywardmonkeys** [comment]
In some hours, yes. Driving for the next 3 hours.

**Comment by waywardmonkeys** [comment]
Here you are ... the schema and generated Rust from schemafy by @marwes.

[Archive.zip](https://github.com/quicktype/quicktype/files/1723493/Archive.zip)

**Comment by Marwes** [comment]
So `schemafy` is done in a really ad-hoc way as I just ran it against the debugserver schema and fixed problems until I got what I needed. After that I never really went back to make it more principled.

**Comment by schani** [comment]
A few observations from the code schemafy generated:

* It gives up on `anyOf` and goes to `serde_json::Value`

* It doesn't handle object types with specified `properties` as well as `additionalProperties`.  An example would be `RangeConfig`.  Same for quicktype.

* It gives up on enums that contain `null`, such as `Config.invalidValues` and goes to `serde_json::Value`.  quicktype crashes on this.

The class/map thing happens for example in `SingleSelection.bind`.

And then we also fumble on `SelectionOperand` which is a recursive type of a kind we can't handle yet.  I have an idea of how to resolve this, though.

Here's the plan, until we have a plan for #493:

- [ ] When unifying class and map types, make a map type whose value is the unification of all the property types and the original map value type.

- [ ] Don't ignore `additionalProperties` on class types and handle them like above.

- [ ] Support the special case of `null` in an enum by removing the `null` from the enum and making a union type of the enum and the null type.

- [ ] Figure out how to handle those recursive types.  My guess is that, instead of unifying types while processing the schema we should instead just build unions that contain multiple class types and then do a graph rewrite that flattens them.  We can do the same thing with the class/map thing.

**Comment by waywardmonkeys** [comment]
@schani You might find it interesting that the Vega Lite schema is generated from TypeScript code via build automation.

**Comment by waywardmonkeys** [comment]
@schani The code is all in https://github.com/vega/vega-lite/tree/master/src ... and they use something called `ts-json-schema-generator`
