### ISSUE TITLE
PHP support

### ISSUE THREAD

**Issue by cosminpopescu14** [quicktype/quicktype#536]
It is possible to add php support ?

**Comment by dvdsgl** [comment]
It is possible! Would you like to contribute yourself or help us find someone to contribute it?

**Comment by schani** [comment]
We're closing new-language issues that find no contributors.

**Comment by dvdsgl** [comment]
@cosminpopescu14 we would love to have someone contribute this. If you're still interested, the best way to make this happen is to promote quicktype in the PHP community and recruit someone willing and able to work on this. We will happily guide them.

**Comment by vearutop** [comment]
Is 3rd party lib usage (JSON schema marshaler/validator) allowed in generated PHP code?
Or generated code should be free from dependencies?

**Comment by schani** [comment]
@vearutop We don't have a strict rule for this.  The guideline is to the native language's JSON processing if it has that, and it's not broken.  If third party dependencies are required then they should be the ones that most people use.  A few examples where we use 3rd party dependencies:

* In C# we use Newtonsoft's Json.NET for JSON processing, because C# doesn't come with JSON support, and everybody uses Json.NET.

* In Java we use Jackson for the same purpose.  Here the choice was not as clear cut - GSON would have been an equally viable alternative.

* In C++ we also use a third-party JSON library, for the same reason.

* In Python we use a small package for date-time parsing.

What is the particular third party library you're considering, and why do you think it's needed?

**Comment by vearutop** [comment]
I think I could implement code generator of PHP classes based on [swaggest/json-schema](https://github.com/swaggest/php-json-schema#php-structured-classes-with-validation) without too much effort. 

I have a code generator written in PHP already ([example](https://github.com/swaggest/php-code-builder/tree/master/tests/src/Tmp/Swagger) of code generated from Swagger JSON Schema).

**Comment by schani** [comment]
So the generate code would be

* generated types
* an invocation to swaggest/json-schema for (de)serialization and validation?

I assume it handles mapping from property names to instance variable names?  How does it deal with [union types](https://app.quicktype.io?share=ohaWVOPoobkYcKfX4tSx)?

**Comment by schani** [comment]
Sounds great!  Should I reopen this issue and assign it to you?  We're happy to help you if you any questions whatsoever [on Slack](https://slack.quicktype.io).

**Comment by vearutop** [comment]
Let me check `quicktype` code and structure first to estimate the scope. Thanks!

**Comment by SidIcarus** [comment]
@vearutop did you make any progress on this?

**Comment by cosminpopescu14** [comment]
> 
> 
> @vearutop did you make any progress on this?

The issue was closed on 6 July 2018

**Comment by vearutop** [comment]
@SidIcarus I'm sorry, I could not make it fast and then I did not have time for this topic.
